image: gitpod/workspace-python-3.11

tasks:
  - name: kedro

    init: |
      make sign-off
      pip install uv
      uv venv
      source .venv/bin/activate
      uv pip install -e /workspace/kedro[test]
      cd /workspace
      kedro new --name project -s spaceflights-pandas --checkout main
      uv pip install -e project
      cd /workspace/kedro
      pre-commit install --install-hooks

    command: |
      clear
      source .venv/bin/activate
      kedro info


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
