# backend/Dockerfile.web
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn NoteCraft_backend.wsgi:application --bind 0.0.0.0:8000"]