name: Deploy Serverless app to AWS

on:
  push:
    branches:
      - main
  
  # To trigger the build manually
  workflow_dispatch:    

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}       

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: configure aws credentials
      #uses: aws-actions/configure-aws-credentials@v1
      #with:
        #role-to-assume: arn:aws:iam::195725532069:role/github-actions-role
        #role-duration-seconds: 900
        #aws-region: ${{ secrets.AWS_REGION }}
        
    # You can now execute commands that use the credentials👇
    - name: Serverless deploy
      #run: sls deploy --stage dev
      run: echo 'hello'
      env:
       AWS_REGION: ${{ secrets.AWS_REGION }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
