name: frontend-docker

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install deps
        run: |
          cd frontend
          npm install
          npm run build
        env:
          CI: false # https://stackoverflow.com/questions/63445967/githubs-action-is-not-building-react-application
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fmeringdal
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/docker/Dockerfile
          push: true
          tags: fmeringdal/nettu-meet-frontend:latest
